# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT

list(APPEND DML_SECURITY_OPTIONS
    /GS
    )

list(APPEND DML_SECURITY_DEFINITIONS)

list(APPEND DML_QUALITY_OPTIONS /W3)

list(APPEND DML_CPP_PRIVATE_OPTIONS)
